using System;
using System.Collections.Generic;

namespace DSharpPlus.Commands;

public class CommandData
{
    // This should be either generated by SGen
    // Or generated by compiled expression
    // Compiled expression is easier but does not allow for AOT.
    // SGen kinda forces us to use .NET Standard 2.0 but allows AOT
    public required Func<object> ExecutionFunc { get; init; }

    public IReadOnlyList<(string?, Type)> Arguments { get; } 
        = new List<(string?, Type)>().AsReadOnly();
}